<?
$aMenuLinks = Array(
    Array(
        "О клинике",
        "/about/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Услуги",
        "/uslugi/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Специалисты",
        "/spetsialisti/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Пациенту",
        "/patsientu/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Контакты",
        "/kontakti/",
        Array(),
        Array(),
        ""
    )
);
?>